galaxy_info:
  role_name: ec2_launch
  author: Deepak Yadav
  description: Role for launching instance on AWS
  min_ansible_version: 2.9
  platforms:
          - name: RedHat
            versions:
                    - all
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
          - aws
          - ec2
          - cloud
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
