---
# vars file for ec2_launch

key: "your key name"
AMI_image: "amazon image tag"
instance_type: "type of instance"
subnet: "your subnet"
aws_access: "AWS acess key"
aws_secret: "your AWS secret key"
region: "ap-south-1"
sg_group: "your security guard tag"
