galaxy_info:
  role_name: k8master      
  author: Deepak Yadav
  description: Role for configuring Master Node
  min_ansible_version: 2.9
  platforms:
  - name: RedHat
    versions:
    - 7
    - 8
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags:
          - master
          - cloud
dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
